apiVersion: v1
kind: ConfigMap
metadata: 
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: shipping
    purpose: shipping-deployment
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: shipping
      purpose: shipping-deployment
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: shipping
        purpose: shipping-deployment
        tier: backend
    spec:
      containers:
      - name: shipping 
        image: sivaphanikumar/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping 
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          # tcpSocket:
          #   port: 8080
          # initialDelaySeconds: 10
          # periodSeconds: 10
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15 
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15  
          # tcpSocket:
          #   port: 8080
          # initialDelaySeconds: 5
          # periodSeconds: 5
---
apiVersion: v1
kind: Service 
metadata:
  name: shipping 
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: shipping
    purpose: shipping-deployment
    tier: backend
  ports:
  - protocol: TCP 
    port: 8080
    targetPort: 8080
