apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: rabbitmq
    purpose: rabbitmq-deployment
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: rabbitmq
      purpose: rabbitmq-deployment
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: rabbitmq
        purpose: rabbitmq-deployment
        tier: db
    spec:
      containers:
      - name: rabbitmq 
        image: rabbitmq:3
        env:
        - name: RABBITMQ_DEFAULT_USER 
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
        imagePullPolicy: Always
        # ports:
        # - containerPort:
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 20
---
apiVersion: v1
kind: Service 
metadata:
  name: rabbitmq 
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: rabbitmq
    purpose: rabbitmq-deployment
    tier: db
  ports:
  - protocol: TCP 
    port: 5672
    targetPort: 5672
