apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mongodb
    purpose: mongodb-deployment
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: mongodb
      purpose: mongodb-deployment
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: mongodb
        purpose: mongodb-deployment
        tier: db
    spec:
      containers:
      - name: mongodb 
        image: sivaphanikumar/mongodb:v1
        # ports:
        # - containerPort:
