apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mysql
    purpose: mysql-deployment
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: mysql
      purpose: mysql-deployment
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: mysql
        purpose: mysql-deployment
        tier: db
    spec:
      containers:
      - name: mysql 
        image: sivaphanikumar/mysql:v1
        imagePullPolicy: Always
        # ports:
        # - containerPort:
        # readinessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf       
      volumes:
          - name: mysql-config
            configMap:
              name: mysql
--- 
# As catalogue need to connect to mondodb we know types of services
# we are choosing ClusterIp service because we are not exposing to public 

apiVersion: v1
kind: Service 
metadata:
  name: mysql 
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: mysql
    purpose: mysql-deployment
    tier: db
  ports:
  - protocol: TCP 
    port: 3306
    targetPort: 3306